config/routes.rb
Rails.application.routes.draw do
  # Pages
  root 'pages#home'
  get 'about', to: 'pages#about', as: :about

  # Files/API calls
  get 'fairul_izwan_cv', to: 'files#fairul_izwan_cv', as: :cv
  post 'bot_message', to: 'projects#bot_message', as: :bot_message

  # Errors
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  resources :projects, only: %i[show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :stacks
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :stacks
  has_many :languages, through: :stacks
end

app/models/stack.rb
class Stack < ApplicationRecord
  belongs_to :language
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  def fairul_izwan_cv
    send_file(
      "#{Rails.root}/public/docs/Fairul-CV.pdf",
      filename: 'Fairul-CV.pdf',
      type: 'application/pdf',
      disposition: 'inline'
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @projects = Project.all.sort_by(&:id)
  end

  def about
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  require 'open-uri'

  def show
    @project = Project.find(params[:id])
    @images_path = Dir.glob("app/assets/images/#{@project.pic_folder}/*").map { |path| "#{@project.pic_folder}/#{File.basename(path)}" }
  end

  def bot_message
    @checker = params[:name].present? || params[:email].present? || params[:message].present?

    if @checker
      message = "Hello! You have a new inquiry.%0A*Name*: #{params[:name]}%0A*Email*: #{params[:email]}%0A*Message*: #{params[:message]}"

      URI.open("https://api.telegram.org/bot#{ENV['TELEGRAM_BOT_API']}/sendMessage?chat_id=#{ENV['TELEGRAM_CHAT_ID']}&parse_mode=Markdown&text=#{message}")
    end

    respond_to do |f|
      f.html
      f.json
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "#{@project.name} | " if @project %>Fairul Izwan</title>
    <!-- Primary Meta Tags -->
    <meta name="title" content="Fairul Izwan | Software Developer">
    <meta name="description" content="I love developing web applications and solving the next problem. And the occasional chai latte ☕️">
    <meta name="Keywords" content="Singapore, Junior Developer, Software Engineering, Software Development, Ruby on Rails, Full-stack Development, Front-end Development, Back-end Development, Technology, Portfolio, Projects, Mid-career Switch">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:title" content="Fairul Izwan | Software Developer">
    <meta property="og:description" content="I love developing web applications and solving the next problem. And the occasional chai latte ☕️">
    <meta property="og:image" content="<%= image_url(asset_path('meta-pic.jpg')) %>">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="<%= request.original_url %>">
    <meta property="twitter:title" content="Fairul Izwan | Software Developer">
    <meta property="twitter:description" content="I love developing web applications and solving the next problem. And the occasional chai latte ☕️">
    <meta property="twitter:image" content="<%= image_url(asset_path('meta-pic.jpg')) %>">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('favicon/favicon.ico') %>


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Rubik:wght@300;500&family=Source+Code+Pro:wght@300&family=Unna:wght@400;700&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% unless ["/404", "/500"].include?(request.path) %>
      <%= render "shared/navbar" %>
    <% end %>
    <%= yield %>
    <% unless ["/404", "/500"].include?(request.path) %>
      <%= render "shared/footer" %>
    <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<!-- Wave -->
<svg class=" about-wave pt-5 pt-lg-0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#fafafa" fill-opacity="1" d="M0,320L40,282.7C80,245,160,171,240,165.3C320,160,400,224,480,261.3C560,299,640,309,720,277.3C800,245,880,171,960,149.3C1040,128,1120,160,1200,186.7C1280,213,1360,235,1400,245.3L1440,256L1440,320L1400,320C1360,320,1280,320,1200,320C1120,320,1040,320,960,320C880,320,800,320,720,320C640,320,560,320,480,320C400,320,320,320,240,320C160,320,80,320,40,320L0,320Z"></path></svg>

<!-- Content -->
<div class="bg-white px-4 px-lg-0 pb-5 m-auto aboutpage">
  <div class="container about">

    <!-- CV -->
    <p><strong>Looking for my <%= link_to "CV", cv_path, class: "link-text", target: "_blank" %>?</strong></p>

    <!-- About Me -->
    <h3>My quick story</h3>
    <p class="subheader"><strong>My Motivation</strong></p>
    <p>My first real exposure to web develoment has been through Swoogo. Back in my previous industry, we have always created event or registration websites for clients and managed data on our end. Although it's good enough, it was never great. Website builders are always geared towards efficiency in exchange for its lack of flexibility and customization.</p>

    <p>It has always irked me that I am confined within the limitations of the builder, which brought me towards the “custom HTML, CSS & JS” portion of the builder, and eventually, web development in general. There, I managed to enhance the websites even more according to the clients' needs (even if it's just increasing the font sizes and including pop-out windows, it was still something!) and it dawned on me:</p>

    <ol>
      <li>how easy it was for me to pick up the syntax</li>
      <li>how much more I want to learn about it</li>
    </ol>

    <p>Ever since then, I have graduated from Le Wagon as a Web Developer and have not stopped learning and developing.</p>

    <p class="subheader"><strong>As a developer</strong></p>
    <p>I pride myself in my code's readability, and I can never push my changes without organizing it first. As someone who has developed 3 web applications in a team, I have come to realize that having code that is not understandable or refactored too much will not just hinder your teammates but yourself too, in the long run.</p>

    <p>I will not hesitate to share my thought processes whenever I find solutions to roadblocks that the team might face. I have always believed that sharing knowledge is also a form of learning.</p>

    <p>I am interested to work on new projects as there are always new learnings that I can take from them. I will always find time to meet fellow developers to hear about their ideas and provide my perspectives.</p>

    <p class="subheader"><strong>As a colleague</strong></p>

    <p>I am always described as an individual that knows how to work and have fun. I am usually deemed as the happy pill but always serious during crunch time. With my background in events management, I am able to discern the client's needs and their long term goals.</p>

    <p>I feel comfortable interacting with stakeholders, from colleagues to clients as my communication skills are excellent. I take pride in my current stint as a Teacher Assistant in Le Wagon, where I was given the opportunity after graduating due to my approachable demeanor and the way I explain the concepts of web development to my peers.</p>

    <p class="subheader"><strong>As a person</strong></p>

    <p>I pride myself in my resourcefulness. I am always approached for perspectives and advice, during and out of office hours. I am curious by nature and passionate about the things I like, and that involves cycling, gymming and of course, web development.</p>
  </div>
</div>

app/views/pages/home.html.erb
<!-- Banner -->
<div class="d-flex flex-column justify-content-center px-4 px-lg-5 banner text-center">
  <h1 class="m-0 display-1 fw-bold">Hello World!</h1>
  <h1 class="mb-4 display-1 fw-bold subheader">I'm <span class="gradient-text">Fairul Izwan</span></h1>
  <div class="row justify-content-center">
    <ul class="p-0 mb-4 col-12 justify-content-center">

      <li>
        <%= link_to "https://github.com/flabroo", target: :_blank, class: "icon" do %>
          <i class="fa-brands fa-2xl fa-square-github"></i>
        <% end %>
      </li>

      <li>
        <%= link_to "https://www.linkedin.com/in/fairul-izwan/", target: :_blank, class: "icon" do %>
          <i class="fa-brands fa-2xl fa-linkedin"></i>
        <% end %>
      </li>

      <li>
        <%= mail_to "izwanrul11@gmail.com", target: :_blank, class: "icon" do %>
          <i class="fa-solid fa-2xl fa-envelope"></i>
        <% end %>
      </li>
    </ul>
    <p class="col-12 col-lg-7">I love developing web applications and solving the next problem. And the occasional chai latte ☕️</p>
  </div>
</div>

<!-- Wave -->
<svg class="home-wave" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#fafafa" fill-opacity="1" d="M0,288L48,272C96,256,192,224,288,197.3C384,171,480,149,576,165.3C672,181,768,235,864,250.7C960,267,1056,245,1152,250.7C1248,256,1344,288,1392,304L1440,320L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"></path></svg>

<!-- Content -->
<div class="px-4 px-lg-0 py-5 m-auto bg-white home-section">
  <div class="container">
    <!-- About Me -->
    <div id="about" class="section home-skills mb-5">
      <h2>About Me</h2>
      <div class="row shadow rounded border p-2 py-3 skills-card">
        <div class="skills-img col-12 col-lg-3 d-flex justify-content-center">
          <%= image_tag "fairul.jpeg", class: "rounded" %>
        </div>
        <div class="skills-con col-12 col-lg-9 d-flex flex-column justify-content-evenly">
          <ul class="p-0 m-0 mb-3 mt-3 mt-lg-0 justify-content-center justify-content-lg-start">
            <li>Ruby on Rails</li>
            <li>Ruby</li>
            <li>SQL</li>
            <li>Javascript</li>
            <li>Stimulus</li>
            <li>React</li>
            <li>HTML</li>
            <li>CSS</li>
          </ul>
          <div class="con-text">
            <h3 class= "text-center text-lg-start">An aspiring Software Developer</h3>
            <p class= "text-center text-lg-start">I am a mid-career switcher after 5 years in the events industry. I realized my passion in web development after tinkering with the “custom settings” of a website builder (which I realize now it's just HTML & CSS). Now, I work on my own projects using Ruby on Rails, Javascript & PostgreSQL. I also teach and guide future developers at Le Wagon.</p>
            <%= link_to "more about me", about_path, class: "link-text" %>
          </div>
        </div>
      </div>
    </div>

    <!-- Projects -->
    <div class="section home-projects">
      <h2 id="projects">Projects</h2>
      <% @projects.each do |project| %>
        <div class="home-project row">
          <div class="project-content pe-5 col-12 col-lg-9 order-2 order-lg-1">
            <h4 class="m-0"><%= project.role %></h4>
            <h3><%= project.name %></h3>
            <ul class="m-0 p-0 my-4">
              <% project.languages.each do |l| %>
                <li><%= l.name %></li>
              <% end %>
            </ul>
            <p><%= project.summary.html_safe %></p>
            <%= link_to "View Project", project_path(project), class: "btn-main d-inline-block m-0" %>
          </div>
          <div class="project-img col-10 m-auto col-lg-3 order-1 order-lg-2">
            <% if project.logo_path %>
              <%= image_tag project.logo_path, class: "mb-3 rounded w-100" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <!-- Contact Me -->

    <!--
    <div data-controller="contact-form" class="section home-contact mb-5 container">
      <h2 class="text-center mx-auto">I'm open to work, let's have a chat!</h2>

      <%#= render "projects/contactform" %>


      <div class="contact-icons d-flex justify-content-evenly">
        <%= mail_to "izwanrul11@gmail.com" do %>
          <i class="fa-solid fa-3x fa-envelope fa-fw"></i>
        <% end %>
        <%= link_to "tel:+6597269434" do %>
          <i class="fa-solid fa-3x fa-phone fa-fw"></i>
        <% end %>
        <%= link_to "https://wa.me/6597269434" do %>
          <i class="fa-3x fa-brands fa-square-whatsapp fa-fw"></i>
        <% end %>
      </div>
    </div>
      -->
  </div>

</div>

app/views/projects/_alert.html.erb
<div class="alert m-auto <%= alert_class %>">
  <%= msg %>
</div>

app/views/projects/_contactform.html.erb
<div data-contact-form-target="alert"></div>

<%= form_with url: "/bot_message", method: :post, id: "bottom-form", data: { action: "submit->contact-form#send", contact_form_target: "form" } do |f| %>
  <%= f.text_field :name, placeholder: "Name" %>
  <%= f.text_field :email, placeholder: "Email Address" %>
  <%= f.text_field :message, placeholder: "Message" %>
  <%= f.submit :Send, class: "input-submit" %>
<% end %>

app/views/projects/about.html.erb
<svg class=" about-wave pt-5 pt-lg-0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#fafafa" fill-opacity="1" d="M0,320L40,282.7C80,245,160,171,240,165.3C320,160,400,224,480,261.3C560,299,640,309,720,277.3C800,245,880,171,960,149.3C1040,128,1120,160,1200,186.7C1280,213,1360,235,1400,245.3L1440,256L1440,320L1400,320C1360,320,1280,320,1200,320C1120,320,1040,320,960,320C880,320,800,320,720,320C640,320,560,320,480,320C400,320,320,320,240,320C160,320,80,320,40,320L0,320Z"></path></svg>
<div class="bg-white px-4 px-lg-0 pb-5 m-auto aboutpage">
  <div class="container about">

    <p><strong>Looking for my <%= link_to "CV", fairul_izwan_cv_path, class: "link-text", target: "_blank" %>?</strong></p>

    <h3>My quick story</h3>
    <p class="subheader"><strong>My Motivation</strong></p>
    <p>My first real exposure to web develoment has been through Swoogo. Back in my previous industry, we have always created event or registration websites for clients and managed data on our end. Although it's good enough, it was never great. Website builders are always geared towards efficiency in exchange for its lack of flexibility and customization.</p>

    <p>It has always irked me that I am confined within the limitations of the builder, which brought me towards the “custom HTML, CSS & JS” portion of the builder, and eventually, web development in general. There, I managed to enhance the websites even more according to the clients' needs (even if it's just increasing the font sizes and including pop-out windows, it was still something!) and it dawned on me:</p>

    <ol>
      <li>how easy it was for me to pick up the syntax</li>
      <li>how much more I want to learn about it</li>
    </ol>

    <p>Ever since then, I have graduated from Le Wagon as a Web Developer and have not stopped learning and developing.</p>

    <p class="subheader"><strong>As a developer</strong></p>
    <p>I pride myself in my code's readability, and I can never push my changes without organizing it first. As someone who has developed 3 web applications in a team, I have come to realize that having code that is not understandable or refactored too much will not just hinder your teammates but yourself too, in the long run.</p>

    <p>I will not hesitate to share my thought processes whenever I find solutions to roadblocks that the team might face. I have always believed that sharing knowledge is also a form of learning.</p>

    <p>I am interested to work on new projects as there are always new learnings that I can take from them. I will always find time to meet fellow developers to hear about their ideas and provide my perspectives.</p>

    <p class="subheader"><strong>As a colleague</strong></p>

    <p>I am always described as an individual that knows how to work and have fun. I am usually deemed as the happy pill but always serious during crunch time. With my background in events management, I am able to discern the client's needs and their long term goals.</p>

    <p>I feel comfortable interacting with stakeholders, from colleagues to clients as my communication skills are excellent. I take pride in my current stint as a Teacher Assistant in Le Wagon, where I was given the opportunity after graduating due to my approachable demeanor and the way I explain the concepts of web development to my peers.</p>

    <p class="subheader"><strong>As a person</strong></p>

    <p>I pride myself in my resourcefulness. I am always approached for perspectives and advice, during and out of office hours. I am curious by nature and passionate about the things I like, and that involves cycling, gymming and of course, web development.</p>
  </div>
</div>

app/views/projects/home.html.erb
<div class="d-flex flex-column justify-content-center px-4 px-lg-5 banner text-center">
  <h1 class="m-0 display-1 fw-bold">Hello World!</h1>
  <h1 class="mb-4 display-1 fw-bold subheader">I'm <span class="gradient-text">Fairul Izwan</span></h1>
  <div class="row justify-content-center">
    <ul class="p-0 mb-4 col-12 justify-content-center">

      <li>
        <%= link_to "https://github.com/flabroo", target: :_blank, class: "icon" do %>
          <i class="fa-brands fa-2xl fa-square-github"></i>
        <% end %>
      </li>

      <li>
        <%= link_to "https://www.linkedin.com/in/fairul-izwan/", target: :_blank, class: "icon" do %>
          <i class="fa-brands fa-2xl fa-linkedin"></i>
        <% end %>
      </li>

      <li>
        <%= mail_to "izwanrul11@gmail.com", target: :_blank, class: "icon" do %>
          <i class="fa-solid fa-2xl fa-envelope"></i>
        <% end %>
      </li>
    </ul>
    <p class="col-12 col-lg-7">I love developing web applications and solving the next problem. And the occasional chai latte ☕️</p>
  </div>
</div>

<svg class="home-wave" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#fafafa" fill-opacity="1" d="M0,288L48,272C96,256,192,224,288,197.3C384,171,480,149,576,165.3C672,181,768,235,864,250.7C960,267,1056,245,1152,250.7C1248,256,1344,288,1392,304L1440,320L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"></path></svg>

<div class="px-4 px-lg-0 py-5 m-auto bg-white home-section">
  <div class="container">
    <div id="about" class="section home-skills mb-5">
      <h2>About Me</h2>
      <div class="row shadow rounded border p-2 py-3 skills-card">
        <div class="skills-img col-12 col-lg-3 d-flex justify-content-center">
          <%= image_tag "fairul.jpeg", class: "rounded" %>
        </div>
        <div class="skills-con col-12 col-lg-9 d-flex flex-column justify-content-evenly">
          <ul class="p-0 m-0 mb-3 mt-3 mt-lg-0 justify-content-center justify-content-lg-start">
            <li>Ruby on Rails</li>
            <li>Ruby</li>
            <li>SQL</li>
            <li>Javascript</li>
            <li>Stimulus</li>
            <li>React</li>
            <li>HTML</li>
            <li>CSS</li>
          </ul>
          <div class="con-text">
            <h3 class= "text-center text-lg-start">An aspiring Software Developer</h3>
            <p class= "text-center text-lg-start">I am a mid-career switcher after 5 years in the events industry. I realized my passion in web development after tinkering with the “custom settings” of a website builder (which I realize now it's just HTML & CSS). Now, I work on my own projects using Ruby on Rails, Javascript & PostgreSQL. I also teach and guide future developers at Le Wagon.</p>
            <%= link_to "more about me", about_path, class: "link-text" %>
          </div>
        </div>
      </div>
    </div>

    <div class="section home-projects">
      <h2 id="projects">Projects</h2>
      <% @projects.each do |project| %>
        <div class="home-project row">
          <div class="project-content pe-5 col-12 col-lg-9 order-2 order-lg-1">
            <h4 class="m-0"><%= project.role %></h4>
            <h3><%= project.name %></h3>
            <ul class="m-0 p-0 my-4">
              <% project.languages.each do |l| %>
                <li><%= l.name %></li>
              <% end %>
            </ul>
            <p><%= project.summary.html_safe %></p>
            <%= link_to "View Project", project_path(project), class: "btn-main d-inline-block m-0" %>
          </div>
          <div class="project-img col-10 m-auto col-lg-3 order-1 order-lg-2">
            <% if project.logo_path %>
              <%= image_tag project.logo_path, class: "mb-3 rounded w-100" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <div data-controller="contact-form" class="section home-contact mb-5 container">
      <h2 class="text-center mx-auto">I'm open to work, let's have a chat!</h2>

      <%= render "contactform" %>

      <!--

      <div class="contact-icons d-flex justify-content-evenly">
        <%= mail_to "izwanrul11@gmail.com" do %>
          <i class="fa-solid fa-3x fa-envelope fa-fw"></i>
        <% end %>
        <%= link_to "tel:+6597269434" do %>
          <i class="fa-solid fa-3x fa-phone fa-fw"></i>
        <% end %>
        <%= link_to "https://wa.me/6597269434" do %>
          <i class="fa-3x fa-brands fa-square-whatsapp fa-fw"></i>
        <% end %>
      </div>
      -->
    </div>
  </div>

</div>

app/views/projects/index.html.erb
<% @projects.each do |project| %>
  <p><%= link_to project.name, project_path(project) %></p>
<% end %>

app/views/projects/show.html.erb
<!-- Wave -->
<svg class="pt-5 pt-lg-0 show-wave" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#fafafa" fill-opacity="1" d="M0,320L40,282.7C80,245,160,171,240,165.3C320,160,400,224,480,261.3C560,299,640,309,720,277.3C800,245,880,171,960,149.3C1040,128,1120,160,1200,186.7C1280,213,1360,235,1400,245.3L1440,256L1440,320L1400,320C1360,320,1280,320,1200,320C1120,320,1040,320,960,320C880,320,800,320,720,320C640,320,560,320,480,320C400,320,320,320,240,320C160,320,80,320,40,320L0,320Z"></path></svg>

<!-- Content -->
<div class="bg-white px-4 px-lg-0 py-5 m-auto showpage">
  <div class="container pb-5">
    <div class="show-title d-flex justify-content-between align-items-center mt -5 flex-column flex-lg-row">
      <h1 class="my-2 text-center text-lg-start"><%= @project.name %></h1>
      <% if @project.url %>
        <%= link_to "View Site", @project.url, target: :_blank, class: "btn btn-primary link-btn" %>
      <% else %>
        <span class="btn btn-secondary my-2">Website Unavailable</span>
      <% end %>
    </div>
    <ul class="m-0 my-2 p-0 mb-5 justify-content-center justify-content-lg-start">
      <% @project.languages.each do |l| %>
        <li><%= l.name %></li>
      <% end %>
    </ul>
    <%= @project.summary.html_safe %>

    <h4>Type</h4>
    <%= @project.kind.html_safe %>

    <h4>Project Purpose and Goal</h4>
    <%= @project.purpose.html_safe %>

    <h4>Web Stack and Explanation</h4>
    <%= @project.explanation.html_safe %>

    <h4>Problems and Thought Process</h4>
    <%= @project.problems.html_safe %>
  </div>

  <div id="carouselExample" class="carousel slide m-auto bg-dark">
    <div class="carousel-inner">
      <% @images_path.each_with_index do |path, index| %>
        <% if index == 0 %>
          <div class="carousel-item active">
            <%= image_tag path, class: "d-block w-100" %>
          </div>
        <% else %>
          <div class="carousel-item">
            <%= image_tag path, class: "d-block w-100" %>
          </div>
        <% end %>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
      <span class="carousel-control-prev-icon dark" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

</div>

app/views/shared/_footer.html.erb
<div class="footer bg-dark p-5 d-flex flex-column flex-lg-row justify-content-around">
  <div class="footer-text d-flex flex-column justify-content-center">
    <h4 class= "text-center text-lg-start">Fairul Izwan</h4>
    <p class= "text-center text-lg-start m-lg-0">© 2023, Built and designed by Fairul Izwan</p>
  </div>
  <div class="footer-contact">
    <h4 class="text-center">Get in touch</h4>
    <ul class="p-0 m-0 justify-content-center">
      <li>
        <%= link_to "https://github.com/flabroo", target: :_blank do %>
          <i class="fa-brands fa-2xl fa-square-github"></i>
        <% end %>
      </li>

      <li>
        <%= link_to "https://www.linkedin.com/in/fairul-izwan/", target: :_blank do %>
          <i class="fa-brands fa-2xl fa-linkedin"></i>
        <% end %>
      </li>

      <li>
        <%= mail_to "izwanrul11@gmail.com", target: :_blank do %>
          <i class="fa-solid fa-2xl fa-envelope"></i>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand position-absolute">
  <div class="container-fluid justify-content-end">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% unless current_page?('/') %>
          <li class="nav-item text-center">
            <%= link_to "\#{ home }", root_path, class: "nav-link" %>
          </li>
        <% end %>
        <% if current_page?('/') %>
          <li class="nav-item text-center">
            <%= link_to "\#{ about }", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item text-center">
            <%= link_to "\#{ projects }", "/#projects", class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>